# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - "main"
  # release:
  #   types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat ./.npmrc
      - run: cat ./.npmrc
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          scope: "@megabeedev"
      - run: npm install
      - run: npm ci
      - name: Replace values
        shell: bash
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: |
          sed -i.back "s|NODE_AUTH_TOKEN|${NODE_AUTH_TOKEN}|g" ./.npmrc
      - run: npm publish --access public
